# Generated by Django 4.1.7 on 2023-09-08 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('category', models.TextField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories')])),
                ('size', models.TextField(choices=[('normal', 'Normal'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
